import type {StructSchema} from '../schema'

export const MarshalZone = [
    {name: 'zoneStart', type: 'float'},
    {name: 'zoneFlag', type: 'int8'}
] as const satisfies StructSchema

export const WeatherForecastSample = [
    {name: 'sessionType', type: 'uint8'},
    {name: 'timeOffset', type: 'uint8'},
    {name: 'weather', type: 'uint8'},
    {name: 'trackTemperature', type: 'int8'},
    {name: 'trackTemperatureChange', type: 'int8'},
    {name: 'airTemperature', type: 'int8'},
    {name: 'airTemperatureChange', type: 'int8'},
    {name: 'rainPercentage', type: 'uint8'}
] as const satisfies StructSchema

export const PacketSessionData = [
    {name: 'weather', type: 'uint8'},
    {name: 'trackTemperature', type: 'int8'},
    {name: 'airTemperature', type: 'int8'},
    {name: 'totalLaps', type: 'uint8'},
    {name: 'trackLength', type: 'uint16'},
    {name: 'sessionType', type: 'uint8'},
    {name: 'trackId', type: 'int8'},
    {name: 'formula', type: 'uint8'},
    {name: 'sessionTimeLeft', type: 'uint16'},
    {name: 'sessionDuration', type: 'uint16'},
    {name: 'pitSpeedLimit', type: 'uint8'},
    {name: 'gamePaused', type: 'uint8'},
    {name: 'isSpectating', type: 'uint8'},
    {name: 'spectatorCarIndex', type: 'uint8'},
    {name: 'sliProNativeSupport', type: 'uint8'},
    {name: 'numMarshalZones', type: 'uint8'},
    {name: 'marshalZones', type: 'array', length: 21, of: MarshalZone},
    {name: 'safetyCarStatus', type: 'uint8'},
    {name: 'networkGame', type: 'uint8'},
    {name: 'numWeatherForecastSamples', type: 'uint8'},
    {name: 'weatherForecastSamples', type: 'array', length: 64, of: WeatherForecastSample},
    {name: 'forecastAccuracy', type: 'uint8'},
    {name: 'aiDifficulty', type: 'uint8'},
    {name: 'seasonLinkIdentifier', type: 'uint32'},
    {name: 'weekendLinkIdentifier', type: 'uint32'},
    {name: 'sessionLinkIdentifier', type: 'uint32'},
    {name: 'pitStopWindowIdealLap', type: 'uint8'},
    {name: 'pitStopWindowLatestLap', type: 'uint8'},
    {name: 'pitStopRejoinPosition', type: 'uint8'},
    {name: 'steeringAssist', type: 'uint8'},
    {name: 'brakingAssist', type: 'uint8'},
    {name: 'gearboxAssist', type: 'uint8'},
    {name: 'pitAssist', type: 'uint8'},
    {name: 'pitReleaseAssist', type: 'uint8'},
    {name: 'ersAssist', type: 'uint8'},
    {name: 'drsAssist', type: 'uint8'},
    {name: 'dynamicRacingLine', type: 'uint8'},
    {name: 'dynamicRacingLineType', type: 'uint8'},
    {name: 'gameMode', type: 'uint8'},
    {name: 'ruleSet', type: 'uint8'},
    {name: 'timeOfDay', type: 'uint32'},
    {name: 'sessionLength', type: 'uint8'},
    {name: 'speedUnitsLeadPlayer', type: 'uint8'},
    {name: 'temperatureUnitsLeadPlayer', type: 'uint8'},
    {name: 'speedUnitsSecondaryPlayer', type: 'uint8'},
    {name: 'temperatureUnitsSecondaryPlayer', type: 'uint8'},
    {name: 'numSafetyCarPeriods', type: 'uint8'},
    {name: 'numVirtualSafetyCarPeriods', type: 'uint8'},
    {name: 'numRedFlagPeriods', type: 'uint8'},
    {name: 'equalCarPerformance', type: 'uint8'},
    {name: 'recoveryMode', type: 'uint8'},
    {name: 'flashbackLimit', type: 'uint8'},
    {name: 'surfaceType', type: 'uint8'},
    {name: 'lowFuelMode', type: 'uint8'},
    {name: 'raceStarts', type: 'uint8'},
    {name: 'tyreTemperature', type: 'uint8'},
    {name: 'pitLaneTyreSim', type: 'uint8'},
    {name: 'carDamage', type: 'uint8'},
    {name: 'carDamageRate', type: 'uint8'},
    {name: 'collisions', type: 'uint8'},
    {name: 'collisionsOffForFirstLapOnly', type: 'uint8'},
    {name: 'mpUnsafePitRelease', type: 'uint8'},
    {name: 'mpOffForGriefing', type: 'uint8'},
    {name: 'cornerCuttingStringency', type: 'uint8'},
    {name: 'parcFermeRules', type: 'uint8'},
    {name: 'pitStopExperience', type: 'uint8'},
    {name: 'safetyCar', type: 'uint8'},
    {name: 'safetyCarExperience', type: 'uint8'},
    {name: 'formationLap', type: 'uint8'},
    {name: 'formationLapExperience', type: 'uint8'},
    {name: 'redFlags', type: 'uint8'},
    {name: 'affectsLicenceLevelSolo', type: 'uint8'},
    {name: 'affectsLicenceLevelMP', type: 'uint8'},
    {name: 'numSessionsInWeekend', type: 'uint8'},
    {name: 'weekendStructure', type: 'array', length: 12, of: 'uint8'},
    {name: 'sector2LapDistanceStart', type: 'float'},
    {name: 'sector3LapDistanceStart', type: 'float'}
] as const satisfies StructSchema
